on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev

name: Linter

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo clippy
        run: cargo clippy -Dwarnings
      - name: cargo fmt
        run: cargo fmt --all -- --check