on: push
name: Linter

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features