on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev

name: Unit tests

jobs:
  unit-tests-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: cargo test && cargo test -p solc-wrapper && cargo test -p solidhunter-lib